app:
    observed_icecast_sources:
        rdwa_die:
            host: live.aurafm.org
            server_name: 'RDWA 107.5'
        rdwa_luc:
            host: live.aurafm.org
            server_name: 'RDWA 101.7'
        radio_blv:
            host: live.aurafm.org
            server_name: 'RadioBLV'
        declic_radio:
            host: live.aurafm.org
            server_name: 'DeclicRADIO'