image: docker:git
services:
  - docker:dind

stages:
  - build
  - start
  - deploy

variables:
  STACK_NAME: isps
  FPM_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}/php-fpm
  CRON_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}/cron

build-docker-image:
  stage: build
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build --cache-from ${FPM_RELEASE_IMAGE}:latest --build-arg APP_VERSION=$CI_COMMIT_TAG -t ${FPM_RELEASE_IMAGE}:latest -t ${FPM_RELEASE_IMAGE}:${CI_COMMIT_TAG} ${CI_PROJECT_DIR} -f .docker/php/Dockerfile
    - docker build --cache-from ${CRON_RELEASE_IMAGE}:latest --build-arg APP_VERSION=$CI_COMMIT_TAG -t ${CRON_RELEASE_IMAGE}:latest -t ${CRON_RELEASE_IMAGE}:${CI_COMMIT_TAG} ${CI_PROJECT_DIR} -f .docker/php/Dockerfile
    - docker push ${FPM_RELEASE_IMAGE}:${CI_COMMIT_TAG}
    - docker push ${FPM_RELEASE_IMAGE}:latest
    - docker push ${CRON_RELEASE_IMAGE}:${CI_COMMIT_TAG}
    - docker push ${CRON_RELEASE_IMAGE}:latest
  when: manual
#  only:
#    - tags

start-prod:
  stage: start
  variables:
    SSH_HOST: ${SSH_HOST}
    SSH_USER: ${SSH_USER}
    SSH_PASSWORD: ${SSH_PASSWORD}
  image: docker:latest
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker stack deploy -c ${CI_PROJECT_DIR}/.docker/docker-compose-liodie.yml ${STACK_NAME}_prod
  environment:
    name: production
    url: https://isps.liodie.fr
  when: manual
#  only:
#    - tags

deploy-to-prod:
  stage: deploy
  variables:
    SSH_HOST: ${SSH_HOST}
    SSH_USER: ${SSH_USER}
    SSH_PASSWORD: ${SSH_PASSWORD}
  image: docker:latest
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker service update --with-registry-auth ${STACK_NAME}_prod_php --update-monitor 10ms --image ${FPM_RELEASE_IMAGE}:${CI_COMMIT_TAG}
  environment:
    name: production
    url: https://isps.liodie.fr
  when: manual
#  only:
#    - tags