image: docker:git
services:
  - docker:dind

stages:
  - build
  - start
  - deploy

variables:
  STACK_NAME: isps
  FPM_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}/php-fpm
  CRON_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}/cron

build-docker-image-amd64:
  stage: build
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build --cache-from ${FPM_RELEASE_IMAGE}:latest --target prod-alpine --build-arg APP_VERSION=${CI_COMMIT_TAG:-test} -t ${FPM_RELEASE_IMAGE}:latest-alpine -t ${FPM_RELEASE_IMAGE}:${CI_COMMIT_TAG:-test}-alpine ${CI_PROJECT_DIR} -f .docker/php/Dockerfile
    - docker build --cache-from ${CRON_RELEASE_IMAGE}:latest --target cron-alpine --build-arg APP_VERSION=${CI_COMMIT_TAG::-test} -t ${CRON_RELEASE_IMAGE}:latest-alpine -t ${CRON_RELEASE_IMAGE}:${CI_COMMIT_TAG:-test}-alpine ${CI_PROJECT_DIR} -f .docker/php/Dockerfile
    - docker push ${FPM_RELEASE_IMAGE}:${CI_COMMIT_TAG:-test}-alpine
    - docker push ${FPM_RELEASE_IMAGE}:latest-alpine
    - docker push ${CRON_RELEASE_IMAGE}:${CI_COMMIT_TAG:-test}-alpine
    - docker push ${CRON_RELEASE_IMAGE}:latest-alpine
  when: manual
#  only:
#    - tags

build-docker-image-arm64:
  stage: build
  variables:
    DOCKER_HOST: ${SSH_USER}@${SSH_HOST}
  script:
    - eval $(ssh-agent -s); echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh; chmod 700 ~/.ssh; ssh-keyscan -t ed25519 $SSH_HOST >> ~/.ssh/known_hosts
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build --cache-from ${FPM_RELEASE_IMAGE}:latest --target prod-alpine --build-arg APP_VERSION=${CI_COMMIT_TAG:-test} -t ${FPM_RELEASE_IMAGE}:latest-alpine -t ${FPM_RELEASE_IMAGE}:${CI_COMMIT_TAG:-test}-alpine ${CI_PROJECT_DIR} -f .docker/php/Dockerfile
    - docker build --cache-from ${CRON_RELEASE_IMAGE}:latest --target cron-alpine --build-arg APP_VERSION=${CI_COMMIT_TAG::-test} -t ${CRON_RELEASE_IMAGE}:latest-alpine -t ${CRON_RELEASE_IMAGE}:${CI_COMMIT_TAG:-test}-alpine ${CI_PROJECT_DIR} -f .docker/php/Dockerfile
    - docker push ${FPM_RELEASE_IMAGE}:${CI_COMMIT_TAG:-test}-alpine
    - docker push ${FPM_RELEASE_IMAGE}:latest-alpine
    - docker push ${CRON_RELEASE_IMAGE}:${CI_COMMIT_TAG:-test}-alpine
    - docker push ${CRON_RELEASE_IMAGE}:latest-alpine
  when: manual

start-prod:
  stage: start
  variables:
    DOCKER_HOST: ${SSH_USER}@${SSH_HOST}
  script:
    - eval $(ssh-agent -s); echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh; chmod 700 ~/.ssh; ssh-keyscan -t ed25519 $SSH_HOST >> ~/.ssh/known_hosts
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker stack deploy -c .docker/docker-compose-liodie.yaml ${STACK_NAME}
  environment:
    name: production
    url: https://isps.liodie.fr
  when: manual
#  only:
#    - tags

deploy-to-prod:
  stage: deploy
  variables:
    DOCKER_HOST: ${SSH_USER}@${SSH_HOST}
  script:
    - eval $(ssh-agent -s); echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh; chmod 700 ~/.ssh; ssh-keyscan -t ed25519 $SSH_HOST >> ~/.ssh/known_hosts
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker service update --with-registry-auth ${STACK_NAME}_php --update-monitor 10ms --image ${FPM_RELEASE_IMAGE}:${CI_COMMIT_TAG}-alpine
    - docker service update --with-registry-auth ${STACK_NAME}_cron --update-monitor 10ms --image ${CRON_RELEASE_IMAGE}:${CI_COMMIT_TAG}-alpine
  environment:
    name: production
    url: https://isps.liodie.fr
  when: manual
#  only:
#    - tags