---
version: '3.9'

services:

  php:
    image: github.com/konandrum/icecast-status-periodic-skimmer/php-fpm:dev
    configs:
      - source: php_conf
        target: /usr/local/etc/php/php.ini
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ..:/var/www/app
      - composer:/var/www/.composer
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1

configs:
  php_conf:
    file: ./php/php.ini

volumes:
  composer: ~
