---
version: '3.9'

services:
  traefik:
    image: traefik:2.11
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.network=traefik_reverse_proxy"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - mode: host
        published: 80
        target: 80
      - mode: host
        published: 443
        target: 443
      - mode: host
        published: 8080
        target: 8080
    deploy:
      endpoint_mode: dnsrr
    networks:
      traefik_reverse_proxy: ~

networks:
  traefik_reverse_proxy:
    attachable: true
    driver: overlay