---
version: '3.9'

services:

  php:
    image: github.com/konandrum/icecast-status-periodic-skimmer/php-fpm:dev
    configs:
      - source: php_conf
        target: /usr/local/etc/php/php.ini
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ..:/var/www/app
      - composer:/var/www/.composer
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    networks:
      db: ~

  cron:
    image: github.com/konandrum/icecast-status-periodic-skimmer/cron:dev
    configs:
      - source: php_conf
        target: /usr/local/etc/php/php.ini
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ..:/var/www/app
      - composer:/var/www/.composer
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    networks:
      db: ~

  postgres:
    image: postgres:${POSTGRES_VERSION:-17}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-isps}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-toor}
      POSTGRES_USER: ${POSTGRES_USER:-root}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    networks:
      db: ~

  adminer:
    image: adminer:latest
    ports:
      - 8026:8080
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      db: ~

configs:
  php_conf:
    file: ./php/php.ini

volumes:
  composer: ~
  postgres_data: ~

networks:
  db: ~